[package]
name = "code_generation"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
serde.workspace = true
serde_yaml.workspace = true
core_types = {path = "../core_types"}

[lib]
proc-macro = true
