version: 0.1.0
schema_diff: minor

structs:
  UserPayload:
    id: string
  
  OrderPayload:
    name: string
    email: string
    cart_id: string

  User:
    id: int
    name: string
    email: string
    created_at: string

  Error:
    description: string
    details: string
    code: int

endpoints:
  create_user:
    uri: https://example.com/user 
    method: POST
    input: UserPayload 
    returns: User
  submit_order:
    uri: https://example.com/order 
    method: POST
    input: OrderPayload
    returns: string

