version: 0.1.0
schema_diff: minor

structs:
  UserPayload:
    id: string

  User:
    id: int
    name: string
    email: string
    created_at: string

  Error:
    description: string
    details: string
    code: int

endpoints:
  create_user:
    uri: https://facebook.com/user 
    method: POST
    input: UserPayload 
    returns: User

